name: eShopOnWeb Build and Deploy

on:
  - push
  - workflow_dispatch

env:
  RESOURCE_GROUP: rg-eshoponweb-Sai-20
  WEBAPP_NAME: eshoponweb-webapp51635062
  DOTNET_VERSION: '8.0.x'

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-quality: 'preview'

      - name: Restore dependencies
        run: dotnet restore ./eShopOnWeb.sln

      - name: Build project
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Run tests
        run: dotnet test ./eShopOnWeb.sln --configuration Release --no-build

      - name: Publish web application
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ./publish
          cd ./publish
          zip -r ../app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: Development
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Website to Azure WebApp using CLI
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --name ${{ env.WEBAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --src-path .net-app/app.zip \
              --type zip
